In [107]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [108]:
df=pd.read_csv("Car details v3.csv")
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [109]:
df.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
torque           222
seats            221
dtype: int64

In [110]:
df['mileage'] = df['mileage'].str[:-5]


In [111]:
df['engine'] = df['engine'].str[:-3]
df['max_power'] = df['max_power'].str[:-4]

In [112]:
df.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner mileage engine max_power  \
0  Individual       Manual   First Owner    23.4   1248        74   
1  Individual       Manual  Second Owner   21.14   1498    103.52   
2  Individual       Manual   Third Owner    17.7   1497        78   
3  Individual       Manual   First Owner    23.0   1396        90   
4  Individual       Manual   First Owner    16.1   1298      88.2   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [113]:
df.shape

(8128, 13)

In [114]:
df=df.dropna()

In [115]:
name_stats=df.groupby('name')['name'].agg('count')
name_stats.sort_values(ascending=False)

name
Maruti Swift Dzire VDI              129
Maruti Alto 800 LXI                  82
Maruti Alto LXi                      71
BMW X4 M Sport X xDrive20d           62
Maruti Swift VDI                     61
                                   ... 
Mahindra TUV 300 T6                   1
Mahindra TUV 300 T6 Plus AMT          1
Mahindra TUV 300 mHAWK100 T8 AMT      1
Mahindra Verito 1.4 G4 BSIV           1
Volvo XC90 T8 Excellence BSIV         1
Name: name, Length: 1982, dtype: int64

In [116]:
len(name_stats[name_stats])

1982

In [117]:
len(name_stats[name_stats<=10])

1837

In [118]:
name_stats_10=name_stats[name_stats<=10]

In [119]:
df.name=df.name.apply(lambda x: 'other' if x in name_stats_10 else x)
len(df.name.unique())

146

In [120]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [121]:
df['name']=le.fit_transform(df['name'])
df['fuel']=le.fit_transform(df['fuel'])
df['seller_type']=le.fit_transform(df['seller_type'])
df['transmission']=le.fit_transform(df['transmission'])
df['owner']=le.fit_transform(df['owner'])
df.head()

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0    88  2014         450000     145500     1            1             1   
1   145  2014         370000     120000     1            1             1   
2   145  2006         158000     140000     3            1             1   
3   145  2010         225000     127000     1            1             1   
4   145  2007         130000     120000     3            1             1   

   owner mileage engine max_power                    torque  seats  
0      0    23.4   1248        74            190Nm@ 2000rpm    5.0  
1      2   21.14   1498    103.52       250Nm@ 1500-2500rpm    5.0  
2      4    17.7   1497        78     12.7@ 2,700(kgm@ rpm)    5.0  
3      0    23.0   1396        90  22.4 kgm at 1750-2750rpm    5.0  
4      0    16.1   1298      88.2     11.5@ 4,500(kgm@ rpm)    5.0

In [122]:
df=df.drop('torque',axis=1)
df.head()

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0    88  2014         450000     145500     1            1             1   
1   145  2014         370000     120000     1            1             1   
2   145  2006         158000     140000     3            1             1   
3   145  2010         225000     127000     1            1             1   
4   145  2007         130000     120000     3            1             1   

   owner mileage engine max_power  seats  
0      0    23.4   1248        74    5.0  
1      2   21.14   1498    103.52    5.0  
2      4    17.7   1497        78    5.0  
3      0    23.0   1396        90    5.0  
4      0    16.1   1298      88.2    5.0

In [158]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

In [124]:
X=df.drop('selling_price',axis=1)
y=df.selling_price

In [143]:
cross_val_score(LinearRegression(),X,y)

array([0.7260414 , 0.68229899, 0.71216688, 0.64863696, 0.67726864])

In [159]:
cross_val_score(RandomForestRegressor(),X,y)

array([0.93654868, 0.93560937, 0.93977229, 0.93644011, 0.93235338])

In [160]:
cross_val_score(AdaBoostRegressor(),X,y)

array([0.82528397, 0.80746749, 0.81202532, 0.80926444, 0.81272584])

In [161]:
cross_val_score(SVR(),X,y)

array([0.26964506, 0.22275405, 0.24657765, 0.2384903 , 0.25309238])

In [162]:
cross_val_score(DecisionTreeRegressor(),X,y)

array([0.8910357 , 0.88398388, 0.90136702, 0.88316329, 0.89234223])