In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [13]:
df.shape

(768, 9)

In [3]:
X=df.drop('Outcome',axis=1)
y=df.Outcome

In [6]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier 

In [7]:
cross_val_score(LinearRegression(),X,y)

array([0.25683342, 0.2575739 , 0.29068798, 0.28108337, 0.29414534])

In [8]:
cross_val_score(LogisticRegression(),X,y)

c:\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

array([0.77272727, 0.74675325, 0.75974026, 0.81699346, 0.75163399])

In [9]:
cross_val_score(SVC(),X,y)

array([0.74675325, 0.73376623, 0.77272727, 0.79084967, 0.75163399])

In [10]:
cross_val_score(RandomForestClassifier(),X,y)

array([0.77922078, 0.73376623, 0.75324675, 0.83660131, 0.75163399])

In [11]:
cross_val_score(DecisionTreeClassifier(),X,y)

array([0.7012987 , 0.65584416, 0.68181818, 0.78431373, 0.7254902 ])

In [17]:
df1=df.iloc[:, :-1]
from sklearn.preprocessing import StandardScaler
scaling=StandardScaler()
scaling.fit(df1)
Scaled_data=scaling.transform(df1)

from sklearn.decomposition import PCA 
principal=PCA(n_components=3)
principal.fit(Scaled_data)
X=principal.transform(Scaled_data)

In [18]:
cross_val_score(LinearRegression(),X,y)

array([0.23473014, 0.15019337, 0.21206858, 0.19486912, 0.22873157])

In [19]:
cross_val_score(LogisticRegression(),X,y)

array([0.76623377, 0.70779221, 0.7012987 , 0.75163399, 0.7254902 ])

In [20]:
cross_val_score(SVC(),X,y)

array([0.72727273, 0.7012987 , 0.70779221, 0.77777778, 0.7254902 ])