In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("train_u6lujuX_CVtuZ9i (1).csv")
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [11]:
df1=df.drop('Loan_ID',axis=1)
df1.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1.Gender=le.fit_transform(df1.Gender) 
df1.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0       1      No          0      Graduate            No             5849   
1       1     Yes          1      Graduate            No             4583   
2       1     Yes          0      Graduate           Yes             3000   
3       1     Yes          0  Not Graduate            No             2583   
4       1      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [13]:
df1.Married=le.fit_transform(df1.Married) 
df1.Education=le.fit_transform(df1.Education) 
df1.Self_Employed=le.fit_transform(df1.Self_Employed) 
df1.ApplicantIncome=le.fit_transform(df1.ApplicantIncome) 
df1.CoapplicantIncome=le.fit_transform(df1.CoapplicantIncome) 
df1.LoanAmount=le.fit_transform(df1.LoanAmount) 
df1.Loan_Status=le.fit_transform(df1.Loan_Status) 

In [15]:
df1=df1.drop('Property_Area',axis=1)
df1.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          0              0              376   
1       1        1          1          0              0              306   
2       1        1          0          0              1              139   
3       1        1          0          1              0               90   
4       1        0          0          0              0              381   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0         203             360.0             1.0   
1                 60          81             360.0             1.0   
2                  0          26             360.0             1.0   
3                160          73             360.0             1.0   
4                  0          94             360.0             1.0   

   Loan_Status  
0            1  
1            0  
2            1  
3            1  
4            1

In [30]:
df1['Dependents'].isnull().sum()

15

In [36]:
df1['Loan_Amount_Term'].isnull().sum()

14

In [40]:
df1['Credit_History'].isnull().sum()

50

In [41]:
df2=df1.drop(['Dependents','Loan_Amount_Term','Credit_History'],axis=1)
df2.head()

Gender  Married  Education  Self_Employed  ApplicantIncome  \
0       1        0          0              0              376   
1       1        1          0              0              306   
2       1        1          0              1              139   
3       1        1          1              0               90   
4       1        0          0              0              381   

   CoapplicantIncome  LoanAmount  Loan_Status  
0                  0         203            1  
1                 60          81            0  
2                  0          26            1  
3                160          73            1  
4                  0          94            1

In [46]:
df2.isnull().sum()

Gender               0
Married              0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Status          0
dtype: int64

In [73]:
y=df2['Loan_Status']
X=df2.drop('Loan_Status',axis=1)

In [74]:
X.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          0              0              376   
1       1        1          1          0              0              306   
2       1        1          0          0              1              139   
3       1        1          0          1              0               90   
4       1        0          0          0              0              381   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0          73             360.0             1.0   
1                 60          81             360.0             1.0   
2                  0          26             360.0             1.0   
3                160          73             360.0             1.0   
4                  0          94             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [51]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [93]:
cross_val_score(LinearRegression(),X,y)

array([ 0.00319319, -0.00990595,  0.00354333, -0.09995972, -0.08393113])

In [94]:
cross_val_score(LogisticRegression(),X,y)

array([0.8021978 , 0.8021978 , 0.79120879, 0.79120879, 0.78888889])

In [95]:
cross_val_score(SVC(),X,y)

array([0.8021978 , 0.8021978 , 0.79120879, 0.79120879, 0.8       ])

In [96]:
cross_val_score(DecisionTreeClassifier(),X,y)

array([0.69230769, 0.7032967 , 0.75824176, 0.73626374, 0.7       ])

In [100]:
cross_val_score(RandomForestClassifier(n_estimators=1000),X,y)

array([0.75824176, 0.76923077, 0.79120879, 0.74725275, 0.75555556])

In [98]:
cross_val_score(MultinomialNB(),X,y)

array([0.57142857, 0.53846154, 0.58241758, 0.49450549, 0.51111111])

In [99]:
from sklearn.ensemble import AdaBoostClassifier
cross_val_score(AdaBoostClassifier(),X,y)

array([0.74725275, 0.78021978, 0.78021978, 0.73626374, 0.7       ])

In [66]:
dfx=df.drop('Loan_ID',axis=1)
dfx.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [67]:
dfx.isnull().sum()

Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [68]:
dfx['Gender'].fillna(dfx['Gender'].mode()[0],inplace=True)
dfx['Married'].fillna(dfx['Married'].mode()[0],inplace=True)
dfx['Dependents'].fillna(dfx['Dependents'].mode()[0],inplace=True)
dfx['Self_Employed'].fillna(dfx['Self_Employed'].mode()[0],inplace=True)
dfx['Credit_History'].fillna(dfx['Credit_History'].mode()[0],inplace=True)
dfx['Loan_Amount_Term'].fillna(dfx['Loan_Amount_Term'].mode()[0],inplace=True)
dfx['LoanAmount'].fillna(dfx['LoanAmount'].mode()[0],inplace=True)



In [69]:
dfx.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [70]:
dfx.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0       120.0             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [71]:
dfx.Gender=le.fit_transform(dfx.Gender) 
dfx.Married=le.fit_transform(dfx.Married) 
dfx.Education=le.fit_transform(dfx.Education) 
dfx.Self_Employed=le.fit_transform(dfx.Self_Employed) 
dfx.ApplicantIncome=le.fit_transform(dfx.ApplicantIncome) 
dfx.CoapplicantIncome=le.fit_transform(dfx.CoapplicantIncome) 
dfx.LoanAmount=le.fit_transform(dfx.LoanAmount) 
dfx.Loan_Status=le.fit_transform(dfx.Loan_Status) 
dfx.Property_Area=le.fit_transform(dfx.Property_Area) 

In [72]:
dfx.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          0              0              376   
1       1        1          1          0              0              306   
2       1        1          0          0              1              139   
3       1        1          0          1              0               90   
4       1        0          0          0              0              381   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0          73             360.0             1.0   
1                 60          81             360.0             1.0   
2                  0          26             360.0             1.0   
3                160          73             360.0             1.0   
4                  0          94             360.0             1.0   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [77]:
y=dfx['Loan_Status']
X=dfx.drop('Loan_Status',axis=1)

In [78]:
X.head()

Gender  Married Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0          0          0              0              376   
1       1        1          1          0              0              306   
2       1        1          0          0              1              139   
3       1        1          0          1              0               90   
4       1        0          0          0              0              381   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0          73             360.0             1.0   
1                 60          81             360.0             1.0   
2                  0          26             360.0             1.0   
3                160          73             360.0             1.0   
4                  0          94             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2

In [84]:
dfx['LoanAmount'].fillna(dfx['LoanAmount'].mean(),inplace=True)


C:\Users\ishan\AppData\Local\Temp\ipykernel_2960\4287565450.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfx['LoanAmount'].fillna(dfx['LoanAmount'].mean(),inplace=True)


In [86]:
dfx.apply(lambda s: pd.to_numeric(s, errors='coerce').notnull().all())


Gender                True
Married               True
Dependents           False
Education             True
Self_Employed         True
ApplicantIncome       True
CoapplicantIncome     True
LoanAmount            True
Loan_Amount_Term      True
Credit_History        True
Property_Area         True
Loan_Status           True
dtype: bool

In [87]:
dfx=dfx.drop('Dependents',axis=1)
dfx.apply(lambda s: pd.to_numeric(s, errors='coerce').notnull().all())


Gender               True
Married              True
Education            True
Self_Employed        True
ApplicantIncome      True
CoapplicantIncome    True
LoanAmount           True
Loan_Amount_Term     True
Credit_History       True
Property_Area        True
Loan_Status          True
dtype: bool

In [90]:
from sklearn.preprocessing import StandardScaler
scaling=StandardScaler()
scaling.fit(dfx)
Scaled_data=scaling.transform(dfx)

In [91]:
y=dfx['Loan_Status']
X=dfx.drop('Loan_Status',axis=1)

In [92]:
X.head()

Gender  Married  Education  Self_Employed  ApplicantIncome  \
0       1        0          0              0              376   
1       1        1          0              0              306   
2       1        1          0              1              139   
3       1        1          1              0               90   
4       1        0          0              0              381   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0          73             360.0             1.0   
1                 60          81             360.0             1.0   
2                  0          26             360.0             1.0   
3                160          73             360.0             1.0   
4                  0          94             360.0             1.0   

   Property_Area  
0              2  
1              0  
2              2  
3              2  
4              2