In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
df=pd.read_csv('heart.csv')
df.head()

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172   
1   49   F           NAP        160          180          0     Normal    156   
2   37   M           ATA        130          283          0         ST     98   
3   48   F           ASY        138          214          0     Normal    108   
4   54   M           NAP        150          195          0     Normal    122   

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0              N      0.0       Up             0  
1              N      1.0     Flat             1  
2              N      0.0       Up             0  
3              Y      1.5     Flat             1  
4              N      0.0       Up             0

In [15]:
df.describe()


Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000   
mean    53.510893  132.396514   198.799564    0.233115  136.809368   
std      9.432617   18.514154   109.384145    0.423046   25.460334   
min     28.000000    0.000000     0.000000    0.000000   60.000000   
25%     47.000000  120.000000   173.250000    0.000000  120.000000   
50%     54.000000  130.000000   223.000000    0.000000  138.000000   
75%     60.000000  140.000000   267.000000    0.000000  156.000000   
max     77.000000  200.000000   603.000000    1.000000  202.000000   

          Oldpeak  HeartDisease  
count  918.000000    918.000000  
mean     0.887364      0.553377  
std      1.066570      0.497414  
min     -2.600000      0.000000  
25%      0.000000      0.000000  
50%      0.600000      1.000000  
75%      1.500000      1.000000  
max      6.200000      1.000000

In [16]:
df[df.Cholesterol>(df.Cholesterol.mean()+3*df.Cholesterol.std())]

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
76    32   M           ASY        118          529          0     Normal   
149   54   M           ASY        130          603          1     Normal   
616   67   F           NAP        115          564          0        LVH   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
76     130              N      0.0     Flat             1  
149    125              Y      1.0     Flat             1  
616    160              N      1.6     Flat             0

In [17]:
df.shape

(918, 12)

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df1=df
df1['ChestPainType']=le.fit_transform(df['ChestPainType'])
df1.head()

Age Sex  ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0   40   M              1        140          289          0     Normal   
1   49   F              2        160          180          0     Normal   
2   37   M              1        130          283          0         ST   
3   48   F              0        138          214          0     Normal   
4   54   M              2        150          195          0     Normal   

   MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0    172              N      0.0       Up             0  
1    156              N      1.0     Flat             1  
2     98              N      0.0       Up             0  
3    108              Y      1.5     Flat             1  
4    122              N      0.0       Up             0

In [19]:
df1['Sex']=le.fit_transform(df['Sex'])
df1['RestingECG']=le.fit_transform(df['RestingECG'])
df1['ExerciseAngina']=le.fit_transform(df['ExerciseAngina'])
df1['ST_Slope']=le.fit_transform(df['ST_Slope'])
df1.head()


Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0   40    1              1        140          289          0           1   
1   49    0              2        160          180          0           1   
2   37    1              1        130          283          0           2   
3   48    0              0        138          214          0           1   
4   54    1              2        150          195          0           1   

   MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0    172               0      0.0         2             0  
1    156               0      1.0         1             1  
2     98               0      0.0         2             0  
3    108               1      1.5         1             1  
4    122               0      0.0         2             0

In [20]:
from sklearn.decomposition import PCA
pca=PCA(0.95)
X_pca=pca.fit_transform(df1.drop('HeartDisease',axis=1))
X_pca

array([[ 92.31094761, -29.44092723],
       [-17.14271772, -13.75128639],
       [ 81.90549795,  38.22744601],
       ...,
       [-69.00407582,  17.3379013 ],
       [ 39.207459  , -33.59828595],
       [-21.43666353, -37.22417628]])

In [21]:
from sklearn.model_selection import train_test_split
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca, df1['HeartDisease'], test_size=0.2, random_state=30)

In [22]:
from sklearn.model_selection import cross_val_score
import sklearn

In [23]:
cross_val_score(sklearn.linear_model.LinearRegression(),X_pca,df1['HeartDisease'])

array([-0.05820236,  0.18874283, -0.12694938,  0.16886405,  0.16052854])

In [24]:
cross_val_score(sklearn.linear_model.LogisticRegression(),X_pca,df1['HeartDisease'])

array([0.60326087, 0.64130435, 0.63586957, 0.7704918 , 0.61202186])

In [25]:
cross_val_score(sklearn.svm.SVC(),X_pca,df1['HeartDisease'])

array([0.64130435, 0.77717391, 0.68478261, 0.70491803, 0.6010929 ])

In [26]:
cross_val_score(sklearn.tree.DecisionTreeClassifier(),X_pca,df1['HeartDisease'])

array([0.60869565, 0.59782609, 0.67934783, 0.6557377 , 0.56284153])

In [29]:
cross_val_score(sklearn.ensemble.RandomForestClassifier(),X_pca,df1['HeartDisease'])

array([0.59782609, 0.70108696, 0.67934783, 0.67759563, 0.61748634])

In [31]:
cross_val_score(sklearn.ensemble.GradientBoostingClassifier(),X_pca,df1['HeartDisease'])

array([0.60326087, 0.65217391, 0.66847826, 0.75956284, 0.6010929 ])