In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('sonar.csv')
df.head()

0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109  \
0  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
1  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
2  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
3  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
4  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   

   0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084  \
0  0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
1  0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
2  0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
3  0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
4  0.3039  ...  0.0045  0.0014  0.0038  0.0013  0.0089  0.0057  0.0027   

   0.0090  0.0032  R  
0  0.0052  0.0044  R  
1  0.0095  0.0078  R  
2  0.0040  0.0117  R  
3  0.0107  0.0094  R  
4  0.0051  0.0062  R  

[5 rows x 61 columns]

In [6]:
df.describe( )

0.0200      0.0371      0.0428      0.0207      0.0954      0.0986  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.029208    0.038443    0.043837    0.054053    0.075105    0.104599   
std      0.023038    0.033040    0.038521    0.046583    0.055669    0.059247   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013300    0.016400    0.018900    0.024450    0.037700    0.066950   
50%      0.022800    0.030800    0.034200    0.044100    0.062000    0.092100   
75%      0.035800    0.048100    0.058200    0.065700    0.101050    0.134150   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

           0.1539      0.1601      0.3109      0.2111  ...      0.0232  \
count  207.000000  207.000000  207.000000  207.000000  ...  207.000000   
mean     0.121591    0.134677    0.177361    0.208245  ...    0.016034   
std      0.061897    0.085340    0.118311    0.134741  ...    0.012027   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080600    0.080350    0.096750    0.111150  ...    0.008350   
50%      0.105600    0.111900    0.152200    0.181000  ...    0.013800   
75%      0.153050    0.169800    0.231500    0.269000  ...    0.020700   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

           0.0027      0.0065      0.0159      0.0072      0.0167      0.0180  \
count  207.000000  207.000000  207.000000  207.000000  207.000000  207.000000   
mean     0.013472    0.010729    0.010917    0.009300    0.008181    0.007771   
std      0.009628    0.007071    0.007310    0.007103    0.005719    0.005756   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007350    0.005050    0.005350    0.004100    0.004400    0.003700   
50%      0.011500    0.009600    0.009300    0.007500    0.006800    0.005900   
75%      0.016750    0.014900    0.014450    0.012100    0.010350    0.010350   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

           0.0084      0.0090      0.0032  
count  207.000000  207.000000  207.000000  
mean     0.007947    0.007936    0.006523  
std      0.006485    0.006196    0.005038  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003650    0.003100  
50%      0.005800    0.006300    0.005300  
75%      0.010400    0.010350    0.008550  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [15]:
df.shape

(207, 61)

In [13]:
df1=df.iloc[:, :-1]
from sklearn.preprocessing import StandardScaler
scaling=StandardScaler()
scaling.fit(df1)
Scaled_data=scaling.transform(df1)

from sklearn.decomposition import PCA 
principal=PCA(n_components=3)
principal.fit(Scaled_data)
x=principal.transform(Scaled_data)
 
print(x.shape)


(207, 3)


In [18]:
X=pd.DataFrame(x)
y=df.iloc[:,-1:]
X

0         1         2
0   -0.450729  7.577721 -1.271445
1    3.893858  6.415978 -0.025868
2    4.592481 -3.120592 -1.800957
3   -0.522855  1.841809 -0.868838
4   -1.219641  3.778474 -1.954311
..        ...       ...       ...
202 -1.206896 -0.968191  3.114469
203 -2.965028 -2.753298  2.488059
204 -2.289583 -2.751940  2.382678
205 -3.112292 -1.849418  2.419094
206 -3.230357 -2.277524  1.695863

[207 rows x 3 columns]

In [19]:
y

R
0    R
1    R
2    R
3    R
4    R
..  ..
202  M
203  M
204  M
205  M
206  M

[207 rows x 1 columns]

In [20]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder  

In [22]:
le=LabelEncoder()
y=le.fit_transform(y)
y=pd.DataFrame(y)

In [23]:
y

0
0    1
1    1
2    1
3    1
4    1
..  ..
202  0
203  0
204  0
205  0
206  0

[207 rows x 1 columns]

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier 

In [25]:
cross_val_score(LinearRegression(),X,y)

array([ 0.        ,  0.        , -0.62683376,  0.        ,  0.        ])

In [26]:
cross_val_score(LogisticRegression(),X,y)

c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1

array([0.57142857, 0.95238095, 0.80487805, 0.7804878 , 0.68292683])

In [27]:
cross_val_score(SVC(),X,y)

c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Python310\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1

array([0.61904762, 0.76190476, 0.75609756, 0.73170732, 0.58536585])

In [28]:
cross_val_score(RandomForestClassifier(),X,y)

c:\Python310\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
c:\Python310\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
c:\Python310\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
c:\Python310\lib\site-packages\sklearn\model_selection\_validation.py:686: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please ch

array([0.61904762, 0.73809524, 0.65853659, 0.70731707, 0.73170732])

In [29]:
cross_val_score(DecisionTreeClassifier(),X,y)

array([0.5       , 0.52380952, 0.65853659, 0.75609756, 0.73170732])